### ISSUE TITLE
City or adress of the station

### ISSUE THREAD

**Issue by janrockstedt** [deler-aziz/fuel_prices_sweden#64]
### System Health details

.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/deler-aziz/fuel_prices_sweden/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After download from havs and added integration in HA it asked for example Ingo and then 95. But not any city or where in the city

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Nothing in the debug
```

### Diagnostics dump

.

**Comment by deler-aziz** [comment]
This integration pulls data from official station websites. However, since these websites do not provide an option to select a city, all displayed prices are base prices. Therefore, it's not possible to obtain prices specific to a particular city or station.

For example, Ingo station publishes its prices on this [link](https://www.ingo.se/v%C3%A5ra-l%C3%A5ga-priser/v%C3%A5ra-l%C3%A5ga-priser/aktuella-listpriser), but as you can see, there is no option to pick a city.

Therefore I am closing this issue
